language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

addons: 
  apt: 
    packages: 
      - libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # SFML
  - sudo apt-get install libsfml-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 DasWahreSchlagerfestConsoleTest.pro
  - make --silent debug
  - ./DasWahreSchlagerfestConsoleTest
  # Console
  - qmake -qt=qt5 DasWahreSchlagerfestConsole.pro
  - make --silent debug
  - qmake -qt=qt5  DasWahreSchlagerfestDesktop.pro
  - make --silent debug
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
  # OCLint
  - ./do_oclint

after_success: 
  - bash <(curl -s https://codecov.io/bash)
